language: ruby
rvm:
- 2.6.3
addons:
- postgresql: '9.6'
services:
- postgresql
before_install:
- gem uninstall bundler
- gem install bundler --version '2.1.4'
- bundle install
before_script:
- psql -c 'create database second_life_test;' -U postgres
- rails db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  skip_cleanup: true
  provider: heroku
  strategy: api
  api_key:
    secure: "TxeFehe38qxlkj0zQsvCa8gKzg3bWKVBXr/cyrl6FQVP1Qwv3gAvupS4bmIsAKoQv3+PQXrmBenCSmt9KW8ABkQ40J47mbIF6X5Yz7S6mCrBJCh+rQ9ivr0MkZBZP8pj7nussv0xkBdJ6XGI2OkmvhMqSxVww85IbHXQRUAxVoU4etpHmM9Cydp+vONCyozhF6f3m+dy6txaHHlUSeQ8F8ey1eaFy4E7XXdB/YZZjRxpeftsF2rDFKLob9U4OTQLX7FH0jB6HHw/euTSn1t/Zpy4NQsHiZ6vx6QZAnFapPk8/diO3/Va4/NUZmNZy7haX/dOhSCS5PiyD0p/XNHhA3P5zutQb5VQxiJrxuPqp4ffO7Apwns484Df848zPJjYN6pnROdPayXqIv1yoPrWdt0U/1QSKzRrAtEhtnN6QZ88UG4kXJgh8QiJxw6OIm9+IBCNAdSNcN3NFLim4CF6xRzlN6bVrHoNt6Mvo8KIQxlr3gfwzgLzxA0S7Ots/S1zoGv5wqLQ9IBXg8kgNf9zX5FLQtDbT9P1GKDsh+SYHEzayF1yspCQkHNAa/ks1SNYZifvJUM2Y/MPTCPLG2ZzReyxySC1S6DliAMbmwlaSs0Bq+S4trCMD414JYweqJTp5HXTEaTOXHqDfaAnjgU5tuNdCmfvVoT5DllMyfDUrpU="
  app: second-life-app
  on:
    repo: jarasmar/Second_Life
