language: ruby
rvm:
- 2.6.3
services:
- postgresql
cache:
- bundler
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rake assets:precompile
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: d+fLBxsIXTnnxw9VZGp+KgCbT7GgWXOOJqaoNFcghMyF5F6Tpd9w+x97QQrAt3NFH7XC9rSlIZ+flu0NqwGG2o8q0PIyZsQPY4r5Oj4ZIx/LVdFjepzqCscz1RZXpG5ytwaVPuwie7CR/6rP+VTeWcaluMBGV7U6Zm0dmeH6jcbN0EfGQOhwFNC3v6DTnYwBAnNUNN5atAklBWWDfLDaGNv8Zd3ovYB9doZO/3trwZ6vGX2DgyBSduI/kXNiCYpo1rYhAme1FYe9AC1xahDxthhjhNyaUVpzy0dbZLBIw3osKomzf0P8j7/K5vnyCdgwQMyjGYj9bkAFMsiM8QoHD+Macf5jmUfcN4RQyMBKhaQVyLv+O05STtBDjfGClrGwYoRBTfj5v/L3EWmMblGZiBANKJGECyibk2eyGOZJIZQyKZEueaao7sR8VTLT0Rmumi+iCe7upEWdeGK6Ij0lvrmt7u7ddR0yfoEC7YF77QySTukxcQ+mW7Igp5RBnI4qCf4akBFTWuCe+7F/FOb/wI5QlO+ICeM8FWDZMSXabFKhao/CRrb8B1wBY0LyIrKtowUURj7cMK2iAl57co07gDa9oJXaYRctc8svieMy6xw8R3AifMAeHEQ9eHB9SqX0R//AVGbz2tY2kdFz2jmi0chsm8NANfgkfLTcyYdHxqk=
  app: second-life-app
  on:
    repo: jarasmar/Second_Life